# Generated by Django 4.0.1 on 2022-07-19 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_user_id_listing_comment_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, default=None, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
